apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "okteto.fullname" . }}-api"
  labels:
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-api"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "okteto.tlsSecretsToReload" . }}"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-api"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-api"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "api"
        app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.api.labels }}
{{ toYaml .Values.api.labels | indent 8 }}
{{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.api.annotations }}
{{ toYaml .Values.api.annotations | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
{{ toYaml .Values.affinity.nodeAffinity | indent 10 }}
        podAntiAffinity:
          {{- if .Values.affinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - "{{ include "okteto.fullname" . }}-api"
              topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - "{{ include "okteto.fullname" . }}-api"
                topologyKey: kubernetes.io/hostname
          {{- end }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- if .Values.tolerations.oktetoPool }}
      tolerations:
      - key: "okteto-node-pool"
        operator: "Equal"
        value: "{{ .Values.tolerations.oktetoPool }}"
        effect: "NoSchedule"
      nodeSelector:
        okteto-node-pool: "{{ .Values.tolerations.oktetoPool }}"
      {{- end }}
      volumes:
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.ingress.tlsSecret" . }}
        {{- if .Values.wildcardCertificate.privateCA.enabled }}
        - name: ca-pemstore
          secret:
            defaultMode: 420
            secretName: {{ .Values.wildcardCertificate.privateCA.secret.name }}
        {{- end }}
      containers:
        - name: api
          image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          args: [ "api" ]
          env:
            - name: OKTETO_INGRESS_INTERNAL_IP
              value: "{{ include "okteto.ingressprivateip" . }}"
            - name: OKTETO_BUILDKIT_INTERNAL_IP
              value: "{{ include "okteto.buildkitprivateip" . }}"
          envFrom:
          - configMapRef:
              name: "{{ include "okteto.fullname" . }}"
          - secretRef:
              name: {{ include "okteto.fullname" . }}
          - secretRef:
              name: "{{ .Values.cloud.secret.name }}"
              optional: true
          volumeMounts:
            - name: tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
          {{- if .Values.wildcardCertificate.privateCA.enabled }}
            - name: ca-pemstore
              mountPath: /etc/ssl/certs/okteto-private-ca.crt
              subPath:  {{ .Values.wildcardCertificate.privateCA.secret.key }}
              readOnly: true
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
