{{- if .Values.unsupported.privateEndpointsOverride.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "okteto.fullname" . }}-private-endpoints"
  labels:
    app.kubernetes.io/component: "private-endpoints"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-private-endpoints"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "okteto.tlsSecretsToReload" . }}"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: {{ .Values.unsupported.privateEndpointsOverride.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-private-endpoints"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-private-endpoints"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "private-endpoints"
        app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.unsupported.privateEndpointsOverride.annotations }}
{{ toYaml .Values.unsupported.privateEndpointsOverride.annotations | indent 8 }}
{{- end }}
    spec:
      affinity:
        nodeAffinity:
{{ toYaml .Values.affinity.nodeAffinity | indent 10 }}
        podAntiAffinity:
          {{- if .Values.affinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "{{ include "okteto.fullname" . }}-private-endpoints"
              topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - "{{ include "okteto.fullname" . }}-private-endpoints"
                topologyKey: kubernetes.io/hostname
          {{- end }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- if .Values.tolerations.oktetoPool }}
      tolerations:
      - key: "okteto-node-pool"
        operator: "Equal"
        value: "{{ .Values.tolerations.oktetoPool }}"
        effect: "NoSchedule"
      nodeSelector:
        okteto-node-pool: "{{ .Values.tolerations.oktetoPool }}"
      {{- end }}
      volumes:
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ .Values.wildcardCertificate.name }}
      containers:
        - name: private-endpoints
          image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.unsupported.privateEndpointsOverride.port }}
              protocol: TCP
          args: [ "private-endpoints" ]
          envFrom:
          - configMapRef:
              name: "{{ include "okteto.fullname" . }}"
          - secretRef:
              name: {{ include "okteto.fullname" . }}
          - secretRef:
              name: "{{ .Values.cloud.secret.name }}"
              optional: true
          volumeMounts:
            - name: tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.unsupported.privateEndpointsOverride.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.unsupported.privateEndpointsOverride.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
          resources:
{{ toYaml .Values.unsupported.privateEndpointsOverride.resources | indent 12 }}
{{- end }}
