{{- if .Values.registry.enabled }}
{{- $publicUrl := include "okteto.public" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "okteto.fullname" . }}-registry"
  labels:
    app.kubernetes.io/component: "registry"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-registry"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "okteto.tlsSecretsToReload" . }}"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-registry"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-registry"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "registry"
        app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.registry.labels }}
{{ toYaml .Values.registry.labels | indent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/registry-secret.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.registry.annotations }}
{{ toYaml .Values.registry.annotations | indent 8 }}
{{- end }}
    spec:
      affinity:
        nodeAffinity:
{{ toYaml .Values.affinity.nodeAffinity | indent 10 }}
        podAntiAffinity:
          {{- if .Values.affinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "{{ include "okteto.fullname" . }}-registry"
              topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - "{{ include "okteto.fullname" . }}-registry"
                topologyKey: kubernetes.io/hostname
          {{- end }}
      {{- if .Values.registry.serviceAccount.create }}
      serviceAccountName: "{{ include "okteto.fullname" . }}-registry"
      {{- else }}
      serviceAccountName: {{ .Values.registry.serviceAccountName }}
      {{- end }}
  {{- if .Values.tolerations.buildPool }}
      tolerations:
      - key: "okteto-node-pool"
        operator: "Equal"
        value: "{{ .Values.tolerations.buildPool }}"
        effect: "NoSchedule"
      nodeSelector:
        okteto-node-pool: "{{ .Values.tolerations.buildPool }}"
  {{- end }}
      volumes:
  {{- if .Values.registry.storage.filesystem.enabled }}
        - name: data
    {{- if .Values.registry.storage.filesystem.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "okteto.fullname" . }}-registry
    {{- else }}
          emptyDir: {}
    {{- end }}
  {{- end }}
        - name: config
          configMap:
            name: {{ template "okteto.fullname" . }}-registry-config
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.ingress.tlsSecret" . }}
  {{- if and .Values.cloud.provider.gcp.enabled (not .Values.cloud.provider.gcp.workloadIdentity.enabled) }}
        - name: gcs-account
          secret:
            defaultMode: 420
            secretName: {{ .Values.cloud.secret.name }}
  {{- end }}
      containers:
        - name: registry
          image: {{ .Values.registry.image.registry }}:{{ .Values.registry.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy}}
          command:
          - sh
          - -c
          - "echo $OKTETO_INGRESS_INTERNAL_IP {{ $publicUrl }} > /etc/hosts && \
          /bin/registry serve /etc/docker/registry/config.yml"
          ports:
            - name: registry
              containerPort: {{ .Values.registry.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.registry.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.registry.port }}
          env:
            - name: OKTETO_INGRESS_INTERNAL_IP
              value: "{{ include "okteto.ingressprivateip" . }}"
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "okteto.fullname" . }}-registry-secret
                  key: haShared
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_AUTH_TOKEN_REALM
              value: "https://{{ $publicUrl }}/auth/registry"
            - name: REGISTRY_AUTH_TOKEN_SERVICE
              value: "okteto-registry"
            - name: REGISTRY_AUTH_TOKEN_ISSUER
              value: "okteto-registry"
            - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
              value: "/run/secrets/tls/tls.crt"

  {{- if .Values.registry.storage.filesystem.enabled }}
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
  {{- else }}
    {{- if .Values.cloud.provider.gcp.enabled }}
            - name: REGISTRY_STORAGE_GCS_BUCKET
              value: {{ required "A valid .Values.cloud.provider.gcp.bucket is required" .Values.cloud.provider.gcp.bucket }}
      {{- if not .Values.cloud.provider.gcp.workloadIdentity.enabled }}
            - name: REGISTRY_STORAGE_GCS_KEYFILE
              value: /run/secrets/gcs/key
      {{- end}}
    {{- else if .Values.cloud.provider.azure.enabled }}
            - name: REGISTRY_STORAGE_AZURE_CONTAINER
              value: {{ required "A valid .Values.cloud.provider.azure.storage.container is required" .Values.cloud.provider.azure.storage.container }}
            - name: REGISTRY_STORAGE_AZURE_ACCOUNTNAME
              value: {{ required "A valid .Values.cloud.provider.azure.storage.accountName is required" .Values.cloud.provider.azure.storage.accountName }}
            - name: REGISTRY_STORAGE_AZURE_ACCOUNTKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloud.secret.name }}
                  key: {{ .Values.cloud.secret.key }}
    {{- else if .Values.cloud.provider.aws.enabled }}
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: {{ required "A valid .Values.cloud.provider.aws.bucket is required" .Values.cloud.provider.aws.bucket }}
            - name: REGISTRY_STORAGE_S3_REGION
              value: {{ .Values.cloud.provider.aws.region }}
      {{- if .Values.cloud.provider.aws.iam.accessKeyID }}
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: {{ .Values.cloud.provider.aws.iam.accessKeyID }}
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloud.secret.name }}
                  key: {{ .Values.cloud.secret.key }}
      {{- end }}
    {{- else if .Values.cloud.provider.digitalocean.enabled}}
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: {{ required "A valid .Values.cloud.provider.digitalocean.space.name is required" .Values.cloud.provider.digitalocean.space.name }}
            - name: REGISTRY_STORAGE_S3_REGION
              value: {{ .Values.cloud.provider.digitalocean.region }}
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              value: {{ .Values.cloud.provider.digitalocean.region }}.digitaloceanspaces.com
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: {{ .Values.cloud.provider.digitalocean.space.accessKeyID }}
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloud.secret.name }}
                  key: {{ .Values.cloud.secret.key }}
    {{- end }}
  {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/etc/docker/registry"
              readOnly: true
            - name: tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
            {{- if .Values.registry.storage.filesystem.enabled }}
            - name: data
              mountPath: /var/lib/registry/
            {{- end }}
            {{- if and .Values.cloud.provider.gcp.enabled (not .Values.cloud.provider.gcp.workloadIdentity.enabled) }}
            - name: gcs-account
              mountPath: /run/secrets/gcs/
              readOnly: true
            {{- end }}
          resources:
{{ toYaml .Values.registry.resources | indent 12 }}
{{- end }}
